eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8093
spring:
  application:
    name: cloud-comsumer
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    solr:
      host: http://localhost:8088/solr
